# needed if: rakefile not found. 
language: generic 

sudo: required
services:
  - docker

before_install:
  - docker build -f -t jfan827/docker-react Dockerfile.dev .

# commands to run on our test suite
script: 
  - docker run -e CI=true jfan827/docker-react npm run test
